spring.application.name=cs5-2
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/APA_Project?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
